name: auto-nia
description: Auto NIA
author: Muhammad Rendra
branding:
  icon: 'play'
  color: 'red'

inputs:
  text:
    description: Any text.
    default: 'Hello NIA'

runs:
  steps:
    run: echo ${{ inputs.text }}
