name: auto-nia
description: Auto NIA
author: mnrendra
branding:
  icon: 'play'
  color: 'purple'

inputs:
  text:
    description: Any text.
    default: 'Hello NIA'

runs:
  steps:
    - name: echo
      run: echo ${{ inputs.text }}
