name: 'auto-nia'
description: 'Nia Amanda.'

branding:
  icon: 'play'
  color: 'blue'

inputs:
  password:
    description: 'A secret password.'
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - run: |
      echo "PASSWORD: ${{ inputs.password }}"
      echo "Base Ref: ${{ github.base_ref }}"
      echo "Head Ref: ${{ github.head_ref }}"
      echo "Ref: ${{ github.ref }}"
      echo "Ref Name: ${{ github.ref_name }}"
      echo "Repository Owner: ${{ github.repository_owner }}"
      echo "Repository Owner Id: ${{ github.repository_owner_id }}"
      echo "Token: ${{ github.token }}"
    shell: bash
