name: 'Auto Nia'
description: 'Auto NIA.'
author: mnrendra
branding:
  icon: 'play'
  color: 'yellow'

inputs:
  text:
    description: 'Any text.'
    default: 'Nia'

runs:
  using: "composite"
  steps:
    - name: 'Print'
      run: echo "Hai ${{ inputs.text }}"
      shell: bash
