name: 'Auto Nia'
description: 'Auto NIA.'

branding:
  icon: 'play'
  color: 'green'

inputs:
  text:
    description: 'Any text.'
    default: 'Nia'
  rahasia:
    description: 'Secret.'
    default: ${{ secrets.RAHASIA }}
  nama:
    description: 'Nama.'
    default: ${{ vars.NAMA }}

runs:
  using: "composite"
  steps:
    - name: 'Print'
      run: echo "Hai ${{ inputs.text }} ${{ inputs.rahasia }} ${{ inputs.nama }}."
      shell: bash
