name: 'auto-nia'
description: 'Nia Amanda.'

branding:
  icon: 'play'
  color: 'blue'

inputs:
  password:
    description: 'A secret password.'
    type: string
  author-name:
    description: 'Author name.'
    type: string
    default: '@${{ github.repository_owner }}'
  author-email:
    description: 'Author email.'
    type: string
    default: '${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com'
  commiter-name:
    description: 'Commiter name.'
    type: string
    default: '@${{ github.repository_owner }}'
  commiter-email:
    description: 'Commiter email.'
    type: string
    default: '${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com'

runs:
  using: "composite"
  steps:
  - run: |
      echo "PASSWORD: ${{ inputs.password }}"
      echo "Base Ref: ${{ github.base_ref }}"
      echo "Head Ref: ${{ github.head_ref }}"
      echo "Ref: ${{ github.ref }}"
      echo "Ref Name: ${{ github.ref_name }}"
      echo "Repository Owner: ${{ github.repository_owner }}"
      echo "Repository Owner Id: ${{ github.repository_owner_id }}"
      echo "Token: ${{ github.token }}"
      echo "======================================================"
      echo "Author Name: ${{ inputs.author-name }}"
      echo "Author Email: ${{ inputs.author-email }}"
      echo "Commiter Name: ${{ inputs.commiter-name }}"
      echo "Commiter Email: ${{ inputs.commiter-email }}"
    shell: bash
